export const BURGER_LOADED_UPDATE = 'BURGER_LOADED_UPDATE';
export const VISIBILITY_UPDATE = 'VISIBILITY_UPDATE';
export const BURGER_ELEMENTS_UPDATE = 'BURGER_ELEMENTS_UPDATE';
export const LOAD_BURGER_SUCCESS = 'LOAD_BURGER_SUCCESS';
export const LOAD_BURGER_FAIL = 'LOAD_BURGER_FAIL';
export const UPDATE_PRICE_STATE = 'UPDATE_PRICE_STATE';
export const UPDATE_BURGER_ELEMENT_ID = 'UPDATE_BURGER_ELEMENT_ID';
